pipeline {
    agent none
    stages {
        stage('Hello Word') {
            agent {
                label "op-machine"
            }
            steps {
                echo "It Work!!!"
            }
        }
    }
}
